/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 8.3 and the Signal Processing Toolbox 6.21.
 * Generated on: 22-Feb-2015 14:57:36
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 64
 * Stable            : Yes
 * Linear Phase      : Yes (Type 2)
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2014a\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   uint16 filter coefficients.
 */
const int filt_n = 64;
const uint16_T filt_coeffs[64] = {
        0,      0,      0,      0,      0,      0,      0,      0,      0,
       37,     87,    145,    211,    283,    361,    446,    535,    628,
      723,    821,    917,   1013,   1105,   1193,   1276,   1352,   1419,
     1477,   1524,   1561,   1586,   1598,   1598,   1586,   1561,   1524,
     1477,   1419,   1352,   1276,   1193,   1105,   1013,    917,    821,
      723,    628,    535,    446,    361,    283,    211,    145,     87,
       37,      0,      0,      0,      0,      0,      0,      0,      0,
        0
};
